### PR TITLE
Updating with newest ITS public extract file

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo ready for your review!

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 it appears the variables on the raw data file has changed slightly which is causing them to not-read in properly (even though there is no log error). I'll investigate and let you know what we need to do to fix it.

**Comment by ahariharan7** [comment]
@rpitingolo I think I made some useful edits (???)

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! I'll take a look.

**Comment by rpitingolo** [comment]
@ahariharan7 I ran a check on ownerpt_2021_01 compared to the last one we did ownerpt_2020_05. Unfortunately it's not just the order of the variables and names that  changed, but some of the values as well. 

These looks OK:

- acceptcode
- acceptcode_new
- del_code
- hstd_code
- ownerpt_extractdat
- nbhd
- part_part
- proptype
- qdrntname
- saletype_new
- sub_nbhd
- usecode
- ui_proptype

These have different values in the data:

- vaclnduse
- mix1class_3d
- mix2class_3d
- mix1txtype
- mix2txtype

This exists as a variable but has no values any more:

- pchildcode

And these variables no longer exist at all:

- basebuild
- bandland

Since these are changes to the raw data itself from the Open Data Portal there's not a whole lot we can do to fix it in these programs I tried to look ahead to see what impact these changes will have on the next steps. It's difficult to know until we run the code and check the log and output. 

So let's go ahead and merge this pull request and batch run it. Then go on to step 2 and we'll troubleshoot from there. If we need to make more changes to the ownerpt_2021_01 dataset then we can open a new bugfix issue if we need to come back to this. Thanks!

**Pull request merged**
