### PR TITLE
Update #50

### PR DESCRIPTION
**Pull request by rpitingolo**
@NeighborhoodInfoDC/review this is the final step in this process. The biggest change is in the FINALIZE_SALES_DATA macro which now uses %Finalize_data_set instead of the legacy code. This is a really complex program / set of macros so I tried to make sure not to mess with it beyond this change.

### CODE REVIEW

**Comment by ptatian** [comment]
@rpitingolo I will review.

**Comment by rpitingolo** [comment]
@ptatian thanks.

**Comment by rpitingolo** [comment]
@ptatian thanks for the review. I'll look into the issues you mentioned.

**Comment by rpitingolo** [comment]
@ptatian hi Peter. Thanks for updating the macro to use %Finalize_sales_data() macro. It seems to be working.

I pushed two commits to resolve the MD/VA/WV tract issue. It looks like this is an unintended consequence of our decision to re-do the formats to include MD/VA/WV rather than create a new format. 

I think you're getting an error on Sales_sum_all.sas because Update_sales_2018_05.sas needs to be batched submitted first. This should have been 2 separate issues / branches. Sorry about that. If it's OK to merge I'll double check it's working after I run the sales file or open a bug-fix issue if there's a problem.

**Comment by ptatian** [comment]
Thanks, @rpitingolo. Do you want me to check anything? Or do you think it's OK to merge?

**Comment by ptatian** [comment]
@rpitingolo OK, then please proceed. Thanks!

**Pull request merged**
