### PR TITLE
Step 4 of the instructions

### PR DESCRIPTION
**Pull request by imull**
I updated the three files
Update_sales_2017_09
Num_units_all
Sales_sum_all

### CODE REVIEW

**Comment by imull** [comment]
@NeighborhoodInfoDC/review

**Comment by rpitingolo** [comment]
@imull thanks. I'll review.

**Comment by ptatian** [comment]
@rpitingolo Has review of this pull request been completed?

**Comment by rpitingolo** [comment]
@ptatian this got stuck because %dollar_convert needs to be updated for 2017. Can you remind me which library it lives in? I assumed General but can't find it.

**Comment by ptatian** [comment]
%dollar_convert is actually in the Urban macro library, which is a whole separate repo. I can look into it.

**Comment by rpitingolo** [comment]
@ptatian thanks. I don't think I know the update process for doing that in github.

**Comment by lhendey** [comment]
I think I did it last time. https://github.com/UI-Research/SASUsersGroup/blob/master/Dollar_convert.sas

**Comment by ptatian** [comment]
@rpitingolo Macro has been updated. If you were working in an interactive session, you should probably close and restart.

**Comment by rpitingolo** [comment]
@ptatian Thanks. It ran without the %dollar_convert error.

**Pull request merged**
