### PR TITLE
I updated the Parcel_geo File

### PR DESCRIPTION
**Pull request by imull**
@NeighborhoodInfoDC/review

### CODE REVIEW

**Comment by rpitingolo** [comment]
@imull I'll review.

**Comment by rpitingolo** [comment]
@imull I'm getting errors that's preventing this from running. Did it run without errors when you tested it?

**Comment by imull** [comment]
I reran it just to check and it’s not giving me any errors.

**Comment by rpitingolo** [comment]
@imull OK thanks. I'll troubleshoot.

**Comment by rpitingolo** [comment]
@imull it looks like your update is in an old template. Can you start over using this template:
D:\DCData\Libraries\RealProp\Prog\Templates\Parcel_geo_ownerpt_yyyy_mm.sas

The reason I was getting errors is because the program requires the MAR library to be created in addition to the RealProp library. If you were testing in an interactive session you may have had MAR created from something else.

**Comment by rpitingolo** [comment]
@imull Hi Irvin - please let me know if you have questions about what needs to be done for this step.

**Comment by imull** [comment]
@rpitingolo I updated the file, Do you want me to start a new pull request?

**Comment by rpitingolo** [comment]
@imull I'll review. No need for a new pull request.

**Comment by rpitingolo** [comment]
@imull please merge this pull request and do a final batch run on L. Then you can move on to step 4.

**Pull request merged**
