### PR TITLE
Update step 3

### PR DESCRIPTION
**Pull request by Woliver01**
@rpitingolo there was an error, please review

### CODE REVIEW

**Comment by Woliver01** [comment]
@rpitingolo do you mean edit L:\Libraries\RealProp\Prog\Templates\Parcel_geo_ownerpt_yyyy_mm? And if so, which part do you want me to edit?

**Comment by rpitingolo** [comment]
@Woliver01 no, please update the templates on D, when we sync it will get pulled over to L.

**Comment by rpitingolo** [comment]
@Woliver01 actually, it looks like the version in the templates folder is OK, so I'm not sure what happened earlier. Just go ahead and merge and batch submit and then move on to the next step. Thanks.

**Comment by Woliver01** [comment]
@rpitingolo ok, yeah I didn't see any obvious mistakes. I'll merge now.

**Pull request merged**
