### PR TITLE
step 2 of updating parcel_base

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo ready for review!

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! I'll take a look.

**Comment by rpitingolo** [comment]
@ahariharan7 it looks like there is an issue relating to the 4 variables that no longer exist on the raw data. Can you please try to remove these variables from the keep list parameter and try running again? 

- basebuild 
- baseland 
- phasecycle 
- streetcode

**Comment by rpitingolo** [comment]
@ahariharan7 turning back to this pull request. Can you please try the edit in my previous comment and let me know if it works? Thanks!

**Comment by ahariharan7** [comment]
@rpitingolo DEL_CODE isn't reading in anything but otherwise it looks good! ready for your review

**Comment by rpitingolo** [comment]
@ahariharan7 thanks! It looks like DEL_CODE exists but is entirely missing on the raw data so there's nothing we can do about that. I'll review.

**Comment by rpitingolo** [comment]
@ahariharan7 I renamed the file back to 2021_01 to be consistent with the ownerpt file. Otherwise, please go ahead and merge, sync, finalize and move on to the next step. Thanks!

**Pull request merged**
