### PR TITLE
Create Parcel_geo_ownerpt_2020_05.sas

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo ready for your review!

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 thanks, I am reviewing now.

**Comment by rpitingolo** [comment]
@ahariharan7 good job. The code runs OK, but there are a few edits still to make. 

1. Move the .sas program from the \updates folder to the main folder (so it's consistent with what you did in step 2)
2. Update `Program:  Parcel_geo_ownerpt_yyyy_mm.sas` in the header 
3. Update `%let revisions = Updated through yyyy-mm;` (this is what updates in the metadata)
4. Switch `%let finalize =` to Y

Once you've made those changes please tag for another review. Thanks!

**Comment by ahariharan7** [comment]
@rpitingolo Thanks for the comments! I have updated the code accordingly.

**Comment by ahariharan7** [comment]
@rpitingolo okay! feeling good about this try!

**Comment by rpitingolo** [comment]
@ahariharan7 thank you! Edits look good and you can go ahead and merge, sync and finalize this one.

**Pull request merged**
