### PR TITLE
Create Parcel_base_ownerpt_2019_09.sas

### PR DESCRIPTION
**Pull request by eleanorble**
@NeighborhoodInfoDC/review ready for review

### CODE REVIEW

**Comment by rpitingolo** [comment]
@eleanorble thanks. I will review.

**Comment by rpitingolo** [comment]
@eleanorble this looks good. Can you please update the header (program name, your name and date) and change the line of code to %let finalize    = Y; ?

Please commit that change I will take one final look. Thanks!

**Comment by eleanorble** [comment]
@rpitingolo Sounds good, I'll work on it tomorrow morning!

**Comment by rpitingolo** [comment]
@eleanorble thank you!

**Comment by eleanorble** [comment]
@rpitingolo Hi! I addressed your comments and didn't see any errors in the log. Let me know if I can run sync on the L drive.

**Comment by rpitingolo** [comment]
Thanks @eleanorble. Please merge this branch, sync on L, bath submit and then move on to step 3.

**Comment by eleanorble** [comment]
@rpitingolo ran the log without any errors. L:\Libraries\Realprop\Prog\Updates\Parcel_base_ownerpt_2019_09.log

**Pull request merged**
