### PR TITLE
Q1 Tax Extract Update

### PR DESCRIPTION
**Pull request by npstrayer**
@rpitingolo Ready for review

### CODE REVIEW

**Comment by rpitingolo** [comment]
@npstrayer thanks. I'll review.

**Comment by rpitingolo** [comment]
@npstrayer please batch submit the two programs and then go on to step 2.

**Comment by rpitingolo** [comment]
@npstrayer as discussed, we will keep these pull request open until the remaining steps are finished. Thanks!

**Comment by npstrayer** [comment]
@rpitingolo Ready for review

**Comment by rpitingolo** [comment]
@npstrayer will review. thanks.

**Pull request merged**
