### PR TITLE
Update for Sept-2016 ownerpt

### PR DESCRIPTION
**Pull request by rpitingolo**
Finished realprop update using ITS data from sept 2016. Sales now current through Q2-2016.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ptatian can you please review / close this issue. Once closed realprop will be up-to-date through Q2-2016.

**Comment by ptatian** [comment]
Rob, I'm confused about what you committed. The commit is for changes to programs Read_itspe_files.sas and Create_new_ownerpt.sas, but are these the programs that should be submitted? I see on L: you have programs Parcel_base_ownerpt_2016_09.sas, Parcel_geo_ownerpt_2016_09.sas, and Update_sales_2016_09.sas, but these aren't part of the GitHub repository. (Also, from before, Parcel_base_ownerpt_2016_04.sas, Parcel_geo_ownerpt_2016_04.sas, and Update_sales_2016_04.sas don't seem to be in the repo, either.) Please clarify. Thank you.

**Comment by rpitingolo** [comment]
Yes, you're right. The programs on the L drive were never part of the Github repository but should be. What's the best way to do this? Should I add them to my repository and then re-commit?

**Comment by ptatian** [comment]
Yes, just copy the programs to your local repository and then commit them. If the other programs aren't meant to be part of the repository, then you can delete them. You don't need to open a new pull request. The changes will just get added to this one.

**Comment by ptatian** [comment]
Temporary programs can also be moved to the Prog/Temp folder, which is not tracked by GitHub, rather than being deleted.

**Comment by rpitingolo** [comment]
I committed the additional programs on develop-#3.

**Comment by ptatian** [comment]
These changes look good. You can go ahead and merge with the Master branch.

**Comment by ptatian** [comment]
You do want to be careful of making sure you commit changes to both programs and macros. I think that you hadn't committed all of the macro changes to I did that.

**Comment by rpitingolo** [comment]
Thanks. Now that everything is properly in the repository it should be smoother next update.

**Pull request merged**
