### PR TITLE
updated %Parcel_base_who_owns()

### PR DESCRIPTION
**Pull request by rpitingolo**
@NeighborhoodInfoDC/review I updated this macro to removed some legacy code and add   %Finalize_data_set

### CODE REVIEW

**Comment by lhendey** [comment]
@NeighborhoodInfoDC/review - i can review.

**Comment by rpitingolo** [comment]
@lhendey thanks.

**Comment by lhendey** [comment]
@rpitingolo  code looks good. The Owncat format isn't fully loading for me. Do i need to run D:\DCDATA\Libraries\Realprop\Prog\Format_$owncat.sas locally or is this something that needs to be batch submitted on L?

**Comment by rpitingolo** [comment]
@lhendey thanks. Not sure about Owncat. I'll check.

**Pull request merged**
