### PR TITLE
Update Create_new_ownerpt.sas

### PR DESCRIPTION
**Pull request by RAGarMir**

### CODE REVIEW

**Comment by rpitingolo** [comment]
@RAGarMir is Step 1 finalized and closed out? It looks like this is using old data. I don't see new files from Step 1 on SAS1.

**Comment by RAGarMir** [comment]
@rpitingolo I ran the sync, checked the Read_itspe_files.sas file to make sure it had updated and batch submitted along with Create_new_ownerpt.sas. Maybe since I ran Create_new_ownerpt.sas, before updating it in this step, that overwrote the data?

**Comment by rpitingolo** [comment]
@RAGarMir it sounds like you followed the process correctly. I see this in the log:

`NOTE: [Finalize_data_set] Not remote batch submit. Data set will not be finalized.`

What kind of environment are you using? Are you logged in directly to SAS1 or using a virtual desktop?

**Comment by RAGarMir** [comment]
@rpitingolo I was in the remote desktop, I had some issues with remote batch submits in the past.

**Comment by rpitingolo** [comment]
@RAGarMir OK, let me see if I can figure out how to get it to work.

**Comment by RAGarMir** [comment]
Actually I think I may have found the issue, I was going through old conversations when I had this issue in the past and I think my problem was that I used the SAS1 virtual desktop, a batch submit from any other remote desktop should work.

**Comment by rpitingolo** [comment]
@RAGarMir OK, give it a try and let me know.

**Comment by RAGarMir** [comment]
@rpitingolo I tried it with a win10secure vm and I still got this in the log.
[Finalize_data_set] Not remote batch submit. Data set will not be finalized.

**Comment by rpitingolo** [comment]
OK we are going to have to sort this out. In the meantime I was able to batch submit step 1 and this code is approved.

**Review by rpitingolo — APPROVED** [review]

**Comment by RAGarMir** [comment]
> OK we are going to have to sort this out. In the meantime I was able to batch submit step 1 and this code is approved.

Great! In the past I was able to use the win11secure vm and that did work, it was unavailable today though. I don't know if that might make a difference.

**Comment by RAGarMir** [comment]
@rpitingolo I think found my issue. I was batch submitting from a mapped drive in the virtual desktop. I created a new network location for SAS1 on my VM and tried again. This time I got this:
[Finalize_data_set] Remote batch submit. Data set will be finalized.

**Pull request merged**
