### PR TITLE
Step 1-B

### PR DESCRIPTION
**Pull request by rpitingolo**
@lhendey this one is now updated to use the permanently saved datasets from Step 1-A.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@lhendey my bad. I had an un-pushed commit. Can you give it another try?

**Comment by lhendey** [comment]
@rpitingolo the var PROPTYPE looks cutoff in the freq- is that how it's supposed to look?

**Comment by rpitingolo** [comment]
@lhendey PROPTYPE is cut off in the raw data so that's exactly how it's being read in. In the past PROPTYPE was a single character (C,F,G,H,R). The %ui_proptype macro uses the variable USECODE to create a property type. So I don't know if PROPTYPE is used for anything or worth trying to recode.

**Review by lhendey — APPROVED** [review]

**Comment by lhendey** [comment]
@rpitingolo okay- good to merge

**Pull request merged**
