### PR TITLE
Develop 1

### PR DESCRIPTION
**Pull request by rpitingolo**
Finished two programs: read_itspe_files.sas and create_new_ownerpt.sas  that will re-create ownerpt using ITS data.

### CODE REVIEW

**Comment by ptatian** [comment]
@rpitingolo The variable Condolot does not exist in the new Ownerpt file, so that's causing an error in the frequencies at the end of the program. Was Condolot meant to be omitted from the final file?

**Comment by rpitingolo** [comment]
@ptatian I didn't see a variable called Condolot in the last several ownerpts. It probably just shouldn't be in the list for %File_info. Not sure why it's there, I just copied that from the code you started setting up.

**Comment by ptatian** [comment]
@rpitingolo Lot_type/lottype also seems to be entirely missing, which is fine because I don't think we use it.

**Comment by ptatian** [comment]
@rpitingolo I cleaned up a few things. Please take a look and let me know if you think I did anything I should not have.

**Comment by rpitingolo** [comment]
I think you cleanups all look fine. Thanks. 

Are you suggesting putting dates on the ITSPE file names? I can certainly turn this into a macro the next time I do an update.

**Comment by ptatian** [comment]
Yes, like we did with the Ownerpt files previously.

**Comment by rpitingolo** [comment]
No problem. I can make that edit in the code.

**Pull request merged**
